name: Daily scraper

on:
  schedule:
    # Runs at 00:00 UTC every day
    # You can adjust the cron expression to your desired time
    # Check crontab.guru for help: https://crontab.guru/
    - cron: '0 0 * * *' 
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest # The operating system to run the job on

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify your Python version (e.g., '3.9', '3.10', '3.11', '3.12')

    - name: Install dependencies (if you have a requirements.txt)
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Run your Python script
      run: python main.py # Replace 'your_script_name.py' with the actual path to your script