name: Daily scraper

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies (if you have a requirements.txt)
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Run your Python script
      env:
        SUPABASE_URL: ${{ secrets.URL }}
        SUPABASE_KEY: ${{ secrets.KEY }}
      run: python main.py